doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: mssql
        server_version: '22.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            OAuth2:
#                is_bundle: false
#                type: attribute                     # https://github.com/symfony/maker-bundle/issues/1152
#                dir: '%kernel.project_dir%/src/OAuth2/Entity'
#                prefix: 'App\OAuth2\Entity'
#                alias: OAuth2
            Actor:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Actor/Entity'
                prefix: 'App\Actor\Entity'
                alias: Actor
            Character:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Character/Entity'
                prefix: 'App\Character\Entity'
                alias: Character
            Movie:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Movie/Entity'
                prefix: 'App\Movie\Entity'
                alias: Movie
            Country:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Country/Entity'
                prefix: 'App\Country\Entity'
                alias: Country
            Genre:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Genre/Entity'
                prefix: 'App\Genre\Entity'
                alias: Genre

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
